### ISSUE TITLE
Rust Support

### ISSUE THREAD

**Issue by javiramos1** [streamnative/function-mesh#358]
Hi, is Rust support in the roadmap?

We are interested in running functions written in Rust.

**Comment by freeznet** [comment]
@javiramos1 thanks for asking, but currently no Rust support for Pulsar Functions, only Java, Python and Golang supported.

**Comment by javiramos1** [comment]
@freeznet Is there any chance of adding this to the roadmap now that streamnative took over the rust crate? https://github.com/streamnative/pulsar-rs

**Comment by freeznet** [comment]
@javiramos1 yes, actually we have the rust & wasm runtime in mind as https://github.com/streamnative/function-mesh/issues/38. But we haven't taken much time on this task due to a lack of engineers in the past few months. But if you do have any requests or ideas on the wasm/rust support, please feel free to comment on the epic issue, and I think we will get back to the issue in the recent future.

**Comment by hpvd** [comment]
maybe kwasm operator can help on this topic, see comments https://github.com/streamnative/function-mesh/issues/38#issuecomment-2166609139
