### ISSUE TITLE
add new GitHub action to cover cases when JarLocation/PyLocation/GoLocation is specified

### ISSUE THREAD

**Issue by jiangpengcheng** [streamnative/function-mesh#401]

**Comment by tpiperatgod** [comment]
as mentioned in [#314](https://github.com/streamnative/function-mesh/issues/314#issuecomment-1163852840), we can use skywalking-e2e-infra to support this action. I will first setup the basic framework for this.

**Comment by tpiperatgod** [comment]
I have done the main work, but I found that the action does not work properly in the environment provided by GitHub, but it works in the local and in the self-hosted runner...it's weird.

run on GitHub: https://github.com/tpiperatgod/function-mesh/actions/runs/2599914361
run on self-hosted runner: https://github.com/tpiperatgod/function-mesh/actions/runs/2599816397

If this issue is still unresolved in the next few days, I would prefer to use the `kubectl wait` command instead of skywalking-e2e-infra to optimize the ci workflows...

**Comment by jiangpengcheng** [comment]
seems like it timed out, maybe can retry for several times

**Comment by tpiperatgod** [comment]
> seems like it timed out, maybe can retry for several times

I've tried but failed...

I plan to keep skywalking-e2e-infra as a local e2e tests framework, what do you think? 🫠

**Comment by jiangpengcheng** [comment]
> > seems like it timed out, maybe can retry for several times
> 
> I've tried but failed...
> 
> I plan to keep skywalking-e2e-infra as a local e2e tests framework, what do you think? 🫠

what does the local mean? it won't be triggered by GitHub actions but can be run manually in our local environment?

**Comment by tpiperatgod** [comment]
> what does the local mean? it won't be triggered by GitHub actions but can be run manually in our local environment?

yes, just type a command like `make e2e`

**Comment by jiangpengcheng** [comment]
I'm ok with that
